theme: jekyll-theme-cayman
title: ModRef 2017
description: "ModRef 2017: The Sixteenth International Workshop on Constraint Modelling and Reformulation"
show_downloads: false
google_analytics: 'UA-99062547-1'
